// Generated by CoffeeScript 1.6.2
(function() {
  define(['jquery', 'underscore', 'backbone', 'router', 'models/controls/switch'], function($, _, Backbone, Router, SwitchControl) {
    var initialize;

    initialize = function() {
      return Router.initialize();
    };
    return {
      initialize: initialize
    };
  });

}).call(this);
