// Generated by CoffeeScript 1.6.2
(function() {
  require.config({
    paths: {
      jquery: 'libs/jquery/jquery.min',
      jqueryui: 'libs/jqueryui/jqueryui.min',
      underscore: 'libs/underscore/underscore.min',
      backbone: 'libs/backbone/backbone.min',
      handlebars: 'libs/handlebars/handlebars',
      text: 'libs/requirejs-text/text'
    },
    shim: {
      backbone: {
        deps: ['underscore', 'jquery'],
        exports: 'Backbone'
      },
      underscore: {
        exports: '_'
      },
      handlebars: {
        exports: 'Handlebars'
      }
    }
  });

  require(['app'], function(App) {
    window.app = {
      app: App,
      collections: {},
      models: {},
      views: {}
    };
    return App.initialize();
  });

}).call(this);
