// Generated by CoffeeScript 1.6.2
(function() {
  define(['jquery', 'underscore', 'backbone', 'views/mainView'], function($, _, Backbone, MainView) {
    var AppRouter, initialize;

    AppRouter = Backbone.Router.extend({
      routes: {
        '': 'landingRoute',
        '*actions': 'defaultAction'
      }
    });
    initialize = function() {
      var app_router;

      app_router = new AppRouter;
      app_router.on('route:landingRoute', function() {
        console.log('landingRoute!');
        return window.app.mainView = new MainView();
      });
      app_router.on('route:defaultAction', function(actions) {
        return console.log('No route: ' + actions);
      });
      Backbone.history.start();
      return console.log(app_router);
    };
    return {
      initialize: initialize
    };
  });

}).call(this);
