// Generated by CoffeeScript 1.6.2
(function() {
  var Models, create, read;

  Models = require(__dirname + '/../models/Controller');

  create = function(req) {
    var controller;

    controller = new Models.Controller({
      name: req.data.name,
      controls: req.data.controls
    });
    return controller.save(function(err) {
      if (!err) {
        console.log('saved!');
        console.log(req.data);
        return req.io.respond({
          success: 'hooray!'
        });
      } else {
        console.log('not saved!');
        return req.io.respond({
          err: err
        });
      }
    });
  };

  read = function(req) {
    console.log(req.data.name);
    return Models.Controller.findOne({
      name: req.data.name
    }, function(err, controller) {
      if (controller) {
        return req.io.respond(controller);
      } else {
        if (!controller) {
          err = 'No controllers found!';
        }
        return req.io.respond({
          err: err
        });
      }
    });
  };

  module.exports = {
    create: create,
    read: read
  };

}).call(this);
