// Generated by CoffeeScript 1.6.2
(function() {
  var app, controller, express, mongoose, port;

  express = require('express.io');

  app = express().http().io();

  mongoose = require('mongoose');

  mongoose.connect('mongodb://nodejitsu:d699ef003dd0c8ed6b579c16f9b25acc@dharma.mongohq.com:10092/nodejitsudb4903400600');

  controller = require('./routes/controller');

  app.post('/login', function(req, res) {
    req.session.loggedin = true;
    return res.end({
      id: 1234
    });
  });

  app.post('/logout', function(req, res) {
    req.session.loggedin = false;
    return res.end('logged out');
  });

  app.io.route('controller', {
    create: function(req) {
      console.log('create a new controller');
      return controller.create(req);
    },
    read: function(req) {
      console.log('read an existing controller');
      return controller.read(req);
    },
    update: function(req) {
      console.log('update an existing controller');
      return console.log(req.data);
    },
    "delete": function(req) {
      console.log('delete an existing controller');
      return console.log(req.data);
    }
  });

  port = 7076;

  app.listen(port, function(err) {
    if (err) {
      throw err;
    }
    return console.log('listening on ' + port);
  });

}).call(this);
