// Generated by CoffeeScript 1.6.2
(function() {
  require.config({
    paths: {
      jquery: '../bower_components/jquery/jquery',
      underscore: '../bower_components/underscore-amd/underscore',
      backbone: '../bower_components/backbone-amd/backbone',
      handlebars: '../bower_components/handlebars/handlebars',
      text: '../bower_components/requirejs-text/text',
      hammer: '../bower_components/hammerjs/dist/hammer.min',
      backboneiobind: '../bower_components/backbone.iobind/dist/backbone.iosync',
      socketio: 'http://api.reactr.co/socket.io/socket.io'
    },
    shim: {
      backbone: {
        deps: ['underscore', 'jquery'],
        exports: 'Backbone'
      },
      underscore: {
        exports: '_'
      },
      handlebars: {
        exports: 'Handlebars'
      },
      hammer: {
        exports: 'Hammer'
      },
      backboneiobind: {
        deps: ['backbone', 'jquery'],
        exports: 'Backbone'
      },
      context: {
        exports: 'Context'
      }
    }
  });

  require(['app'], function(App) {
    window.app = {
      app: App,
      collections: {},
      models: {},
      views: {}
    };
    return App.initialize();
  });

}).call(this);
