// Generated by CoffeeScript 1.6.2
(function() {
  define(['jquery', 'underscore', 'backbone', 'models/controllerModel', 'views/controllerView'], function($, _, Backbone, ControllerModel, ControllerView) {
    var AppRouter, initialize;

    AppRouter = Backbone.Router.extend({
      routes: {
        ':controller': 'controllerRoute'
      }
    });
    initialize = function() {
      var app_router;

      app_router = new AppRouter;
      app_router.on('route:landingRoute', function() {
        console.log('landingRoute!');
        return window.app.views.main = new MainView;
      });
      app_router.on('route:controllerRoute', function(name) {
        var controller;

        console.log('controller route: ' + name);
        controller = window.app.models.controller = new ControllerModel({
          name: name
        });
        return window.app.views.controller = new ControllerView({
          model: window.app.models.controller
        });
      });
      return Backbone.history.start();
    };
    return {
      initialize: initialize
    };
  });

}).call(this);
