// Generated by CoffeeScript 1.6.2
(function() {
  define(['jquery', 'underscore', 'backbone', 'views/controls/base'], function($, _, Backbone, BaseView) {
    var AccelerometerView;

    AccelerometerView = BaseView.extend({
      setup: function() {
        return this.model.set('description', 'Tilt your device to send accelerometer data.');
      },
      onclick: function() {
        var _this = this;

        this.$el.addClass('control-active');
        return setTimeout(function() {
          return _this.$el.removeClass('control-active');
        }, 200);
      }
    });
    return AccelerometerView;
  });

}).call(this);
