// Generated by CoffeeScript 1.6.2
(function() {
  define(['jquery', 'underscore', 'backbone', 'views/controls/base'], function($, _, Backbone, BaseView) {
    var Button;

    Button = BaseView.extend({
      setup: function() {
        return this.model.set('description', 'Tap to send event.');
      }
    });
    return Button;
  });

}).call(this);
