// Generated by CoffeeScript 1.6.2
(function() {
  define(['jquery', 'underscore', 'backbone', 'views/controls/base'], function($, _, Backbone, BaseView) {
    var GpsView;

    GpsView = BaseView.extend({
      setup: function() {
        return this.model.set('description', 'Drag the slider up or down to send data.');
      }
    });
    return GpsView;
  });

}).call(this);
