// Generated by CoffeeScript 1.6.2
(function() {
  define(['jquery', 'underscore', 'backbone', 'views/controls/base'], function($, _, Backbone, BaseView) {
    var LocationView;

    LocationView = BaseView.extend({
      setup: function() {
        return this.model.set('description', 'Go on a walk.');
      }
    });
    return LocationView;
  });

}).call(this);
