// Generated by CoffeeScript 1.6.2
(function() {
  define(['jquery', 'underscore', 'backbone', 'views/controls/base'], function($, _, Backbone, BaseView) {
    var SliderView;

    SliderView = BaseView.extend({
      setup: function() {
        return this.model.set('description', 'Take this control out.');
      }
    });
    return SliderView;
  });

}).call(this);
