// Generated by CoffeeScript 1.6.2
(function() {
  define(['jquery', 'underscore', 'backbone', 'views/controls/base'], function($, _, Backbone, BaseView) {
    var SwitchView;

    SwitchView = BaseView.extend({
      setup: function() {
        return this.model.set('description', 'Press to toggle.');
      }
    });
    return SwitchView;
  });

}).call(this);
