// Generated by CoffeeScript 1.6.2
(function() {
  define(['jquery', 'underscore', 'backbone', 'play/models/controlModel', 'play/collections/controls', 'play/views/controls/switch', 'play/views/controls/button'], function($, _, Backbone, ControlModel, ControlsCollection, SwitchView, ButtonView) {
    var ControllerModel;

    ControllerModel = Backbone.Model.extend({
      initialize: function() {
        return console.log('new controller model!');
      },
      fetchData: function() {
        var butt, swit;

        swit = new ControlModel({
          viewProto: SwitchView,
          value: 0,
          icon: 'icon-magnet',
          name: 'my-switch',
          'name-display': 'My Switch'
        });
        butt = new ControlModel({
          viewProto: ButtonView,
          type: 'button',
          icon: 'icon-arrow-up',
          name: 'my-button',
          'name-display': 'My Button'
        });
        this.collection = new ControlsCollection([swit, butt]);
        return this.trigger('controller:load');
      }
    });
    return ControllerModel;
  });

}).call(this);
