// Generated by CoffeeScript 1.6.2
(function() {
  define(['jquery', 'underscore', 'backbone', 'play/views/controls/base'], function($, _, Backbone, BaseView) {
    var SwitchView;

    SwitchView = BaseView.extend({
      onclick: function() {
        if (this.$el.hasClass('control-active')) {
          return this.$el.removeClass('control-active');
        } else {
          return this.$el.addClass('control-active');
        }
      }
    });
    return SwitchView;
  });

}).call(this);
