// Generated by CoffeeScript 1.6.2
(function() {
  define(['jquery', 'underscore', 'backbone', 'views/controls/switch', 'views/controls/button', 'views/controls/touchpad', 'views/controls/accelerometer', 'views/controls/slider', 'views/controls/gps'], function($, _, Backbone, SwitchView, ButtonView, TouchpadView, AccelerometerView, SliderView, GpsView) {
    var ControlModel;

    ControlModel = Backbone.Model.extend({
      initialize: function() {
        var type, viewProto;

        type = this.get('type');
        viewProto = (function() {
          switch (false) {
            case type !== 'switch':
              return SwitchView;
            case type !== 'button':
              return ButtonView;
            case type !== 'touchpad':
              return TouchpadView;
            case type !== 'accelerometer':
              return AccelerometerView;
            case type !== 'slider':
              return SliderView;
            case type !== 'gps':
              return GpsView;
          }
        })();
        return this.set('viewProto', viewProto);
      }
    });
    return ControlModel;
  });

}).call(this);
